<?php require_once __DIR__ . '/../inc/config.php'; require_once __DIR__ . '/../inc/db.php'; require_once __DIR__ . '/../inc/helpers.php'; $id = (int)($_GET['id'] ?? 0); $stmt = $pdo->prepare('SELECT p.*, u.username FROM blogPost p JOIN user u ON p.user_id = u.id WHERE p.id = :id LIMIT 1'); $stmt->execute([':id'=>$id]); $post = $stmt->fetch(); if (!$post){ $_SESSION['flash']='Not found'; header('Location: '.BASE_URL); exit; } $tagQ = $pdo->prepare('SELECT t.name FROM tag t JOIN post_tag pt ON t.id = pt.tag_id WHERE pt.post_id = :pid'); $tagQ->execute([':pid'=>$id]); $tags = array_column($tagQ->fetchAll(),'name'); $comQ = $pdo->prepare('SELECT cm.*, u.username FROM comment cm JOIN user u ON cm.user_id = u.id WHERE cm.post_id = :pid ORDER BY cm.created_at ASC'); $comQ->execute([':pid'=>$id]); $comments = $comQ->fetchAll(); $likeCount = $pdo->prepare('SELECT COUNT(*) FROM post_like WHERE post_id = :pid'); $likeCount->execute([':pid'=>$id]); $count = $likeCount->fetchColumn(); $liked=false; if (is_logged_in()){ $lk = $pdo->prepare('SELECT id FROM post_like WHERE post_id=:pid AND user_id=:uid'); $lk->execute([':pid'=>$id,':uid'=>$_SESSION['user']['id']]); $liked = (bool)$lk->fetch(); } require_once __DIR__ . '/../inc/header.php'; ?><article class="post"><h1><?php echo htmlspecialchars($post['title']);?></h1><div class="meta">By <?php echo htmlspecialchars($post['username']);?> • <?php echo date('F j, Y', strtotime($post['created_at']));?></div><?php if ($post['image']): ?>
  <img
    src="<?php echo BASE_URL;?>uploads/<?php echo htmlspecialchars($post['image']); ?>"
    alt="<?php echo htmlspecialchars($post['title']); ?>"
    class="post-detail-img"
  >
<?php endif; ?>
<div class="post-content"><?php echo $post['content']; ?></div><div class="post-tags"><?php foreach($tags as $t) echo '<span class="tag">'.htmlspecialchars($t).'</span> ';?></div><div style="margin-top:12px"><?php if (isset($count)){} ?>
<button class="like-btn <?php echo isset($liked) && $liked ? 'liked' : ''; ?>" data-post-id="<?php echo (int)$post['id']; ?>" data-csrf="<?php echo csrf_token(); ?>" type="button">
  <span class="count"><?php echo (int)$count; ?></span> ♥
</button></div><?php if (is_logged_in() && (($_SESSION['user']['id'] ?? 0) == $post['user_id'] || is_admin())): ?><p><a href="<?php echo BASE_URL;?>posts/edit.php?id=<?php echo $post['id']; ?>">Edit post</a></p><?php endif; ?><section class="comments"><h3>Comments (<?php echo count($comments);?>)</h3><?php foreach($comments as $c): ?><div class="comment"><div class="comment-meta"><?php echo htmlspecialchars($c['username']);?> • <?php echo date('M j, Y H:i', strtotime($c['created_at']));?></div><div class="comment-body"><?php echo nl2br(htmlspecialchars($c['body']));?></div></div><?php endforeach; ?><?php if (is_logged_in()): ?><form method="post" action="<?php echo BASE_URL;?>posts/comment_add.php" class="form"><input type="hidden" name="_csrf" value="<?php echo csrf_token();?>"><input type="hidden" name="post_id" value="<?php echo $post['id'];?>"><label>Add comment<textarea name="body" required rows="4"></textarea></label><button type="submit">Post comment</button></form><?php else: ?><p><a href="<?php echo BASE_URL;?>auth/login.php">Login</a> to comment.</p><?php endif; ?></section></article><?php require_once __DIR__ . '/../inc/footer.php'; ?>